# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-09 07:08
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('uid', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('myurl', models.CharField(max_length=60, unique=True)),
                ('image', models.ImageField(blank=True, height_field='imgheight', null=True, upload_to=blog.models.upload_loc, width_field='imgwidth')),
                ('imgwidth', models.IntegerField(default=0)),
                ('imgheight', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('tag', models.CharField(choices=[('Science', 'Science'), ('Technology', 'Technology'), ('Arts', 'Arts'), ('News', 'News'), ('Event', 'Event'), ('Music', 'Music')], default='Science', max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
