# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-01 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('Science', 'Science'), ('Technology', 'Technology'), ('Arts', 'Arts'), ('News', 'News'), ('Event', 'Event'), ('Music', 'Music')], default='Science', max_length=15),
        ),
    ]
